import type { Metadata } from "next";

export const metadata: Metadata = {
    title: 'Thank You - Study Monk',
    description: 'Generated by Next.js',
  }


export default function StoryLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
        <>
          {children}
        </>
    )
}