import type { Metadata } from "next";

export const metadata: Metadata = {
    title: ' Terms of Service Agreement',
    description: 'Generated by Next.js',
  }


export default function TermsServiceLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
        <>
          {children}
        </>
    )
}